import type { JobPost } from '../types/jobs';

function daysAgoIso(days: number) {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
}

function daysFromNowIso(days: number) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString();
}

const growthPublishedAt = daysAgoIso(7);
const seoPublishedAt = daysAgoIso(6);
const atlassianPublishedAt = daysAgoIso(5);
const commbankPublishedAt = daysAgoIso(4);
const doordashPublishedAt = daysAgoIso(3);
const nikePublishedAt = daysAgoIso(2);
const applePublishedAt = daysAgoIso(1);

export const SAMPLE_PUBLISHED_JOBS: JobPost[] = [
  {
    id: 'sample-head-growth-analytics-crypto-com',
    slug: 'head-of-growth-analytics-crypto-com',
    status: 'published',
    packageType: 'amplified',
    paymentStatus: 'paid',
    title: 'Head of Growth Analytics',
    companyName: 'Crypto.com',
    companyWebsite: 'https://crypto.com',
    brandLogoUrl: null,
    brandPrimaryColor: '#0d1f4e',
    brandSecondaryColor: '#103f93',
    locationText: 'Sydney, New South Wales, Australia',
    locationMode: 'hybrid',
    employmentType: 'full-time',
    seniorityLevel: 'director',
    salaryMin: 220000,
    salaryMax: 280000,
    salaryCurrency: 'AUD',
    salaryPeriod: 'year',
    summary:
      'Lead marketing measurement and analytics for growth, including attribution strategy, forecasting, and AI-enabled automation that turns data into clear decisions.',
    responsibilities: [
      'Define and own the marketing intelligence roadmap across growth and performance marketing.',
      'Lead a cross-functional team of analysts, engineers, and data practitioners.',
      'Design and operationalize attribution frameworks (including MTA and MMM where relevant).',
      'Build predictive models for LTV, churn, and campaign incrementality.',
      'Automate recurring reporting and campaign-insight workflows.',
      'Partner with Growth, Product, and Finance leaders on channel and budget decisions.',
    ].join('\n'),
    requirements: [
      '8+ years in growth analytics, marketing analytics, or marketing science.',
      'Strong hands-on experience with attribution, incrementality, and measurement design.',
      'Advanced SQL and data warehouse skills (BigQuery preferred).',
      'Experience deploying predictive models into business workflows.',
      'Excellent stakeholder management with senior and executive teams.',
      'Track record building and mentoring high-performing analytics teams.',
    ].join('\n'),
    niceToHave: [
      'Experience with generative AI workflows for insight generation and storytelling.',
      'Fintech, marketplace, or other high-growth product experience.',
    ].join('\n'),
    applicationMode: 'both',
    externalApplyUrl:
      'https://www.linkedin.com/jobs/search/?keywords=Head%20of%20Growth%20Analytics%20Crypto.com',
    easyApplyEmail: 'careers@crypto.com',
    easyApplyFields: {
      collectName: true,
      collectEmail: true,
      collectCv: true,
      collectLinkedin: true,
      collectCoverLetter: true,
    },
    applicationDeadline: daysFromNowIso(21),
    contactName: 'Crypto.com Talent Team',
    postedByEmail: 'jobs@dawsydney.org.au',
    postedByUserId: null,
    stripeCheckoutSessionId: null,
    publishedAt: growthPublishedAt,
    publishExpiresAt: daysFromNowIso(83),
    reviewNote: null,
    lastReviewedByEmail: null,
    lastReviewedAt: null,
    createdAt: growthPublishedAt,
    updatedAt: daysAgoIso(2),
  },
  {
    id: 'sample-seo-specialist-rd',
    slug: 'seo-specialist-rd',
    status: 'published',
    packageType: 'standard',
    paymentStatus: 'paid',
    title: 'SEO Specialist',
    companyName: 'RD',
    companyWebsite: 'https://www.linkedin.com/company/rd',
    brandLogoUrl: null,
    brandPrimaryColor: '#1e293b',
    brandSecondaryColor: '#334155',
    locationText: 'Remote (Europe-friendly timezone overlap)',
    locationMode: 'remote',
    employmentType: 'full-time',
    seniorityLevel: 'senior',
    salaryMin: 95000,
    salaryMax: 125000,
    salaryCurrency: 'AUD',
    salaryPeriod: 'year',
    summary:
      'Own SEO strategy and execution end-to-end, from technical audits and content planning to ranking growth and measurable organic pipeline impact.',
    responsibilities: [
      'Own technical, on-page, and off-page SEO planning and execution.',
      'Run audits and resolve crawl, indexing, and site-performance issues.',
      'Drive keyword, content, and internal-linking strategy with the content team.',
      'Monitor rankings, traffic, and conversion trends across priority pages.',
      'Collaborate with design and development to implement SEO best practices.',
      'Report performance insights and recommendations to marketing leadership.',
    ].join('\n'),
    requirements: [
      '4+ years of hands-on SEO experience in a growth-focused environment.',
      'Strong technical SEO fundamentals and content optimization skills.',
      'Experience with GA4, Google Search Console, and tools like Ahrefs or Semrush.',
      'Confident with data analysis and turning insights into action plans.',
      'Clear communicator who can work cross-functionally with content and product teams.',
      'Proven track record improving rankings and organic business outcomes.',
    ].join('\n'),
    niceToHave: [
      'Agency or high-growth startup experience.',
      'Familiarity with AI-assisted content research and optimization workflows.',
    ].join('\n'),
    applicationMode: 'both',
    externalApplyUrl:
      'https://www.linkedin.com/jobs/search/?keywords=SEO%20Specialist%20RD',
    easyApplyEmail: 'careers@rd.digital',
    easyApplyFields: {
      collectName: true,
      collectEmail: true,
      collectCv: true,
      collectLinkedin: true,
      collectCoverLetter: true,
    },
    applicationDeadline: daysFromNowIso(28),
    contactName: 'RD Hiring Team',
    postedByEmail: 'jobs@dawsydney.org.au',
    postedByUserId: null,
    stripeCheckoutSessionId: null,
    publishedAt: seoPublishedAt,
    publishExpiresAt: daysFromNowIso(84),
    reviewNote: null,
    lastReviewedByEmail: null,
    lastReviewedAt: null,
    createdAt: seoPublishedAt,
    updatedAt: daysAgoIso(1),
  },
  {
    id: 'sample-senior-product-analyst-atlassian',
    slug: 'senior-product-analyst-atlassian',
    status: 'published',
    packageType: 'amplified',
    paymentStatus: 'paid',
    title: 'Senior Product Analyst',
    companyName: 'Atlassian',
    companyWebsite: 'https://www.atlassian.com',
    brandLogoUrl: null,
    brandPrimaryColor: '#0052cc',
    brandSecondaryColor: '#0747a6',
    locationText: 'Sydney, NSW (Hybrid)',
    locationMode: 'hybrid',
    employmentType: 'full-time',
    seniorityLevel: 'senior',
    salaryMin: 165000,
    salaryMax: 210000,
    salaryCurrency: 'AUD',
    salaryPeriod: 'year',
    summary:
      'Partner with product managers and engineers to define metrics, run experiments, and translate product usage patterns into roadmap decisions for collaboration products.',
    responsibilities: [
      'Own product KPI definitions and dashboard quality for a core product area.',
      'Design and evaluate A/B tests, feature rollouts, and retention initiatives.',
      'Work with data engineers to improve event tracking and model reliability.',
      'Produce insight narratives for quarterly planning and executive reviews.',
      'Coach product squads on metric interpretation and decision hygiene.',
    ].join('\n'),
    requirements: [
      '5+ years in product analytics, growth analytics, or decision science.',
      'Strong SQL and experimentation fundamentals.',
      'Experience working with event analytics and product telemetry.',
      'Ability to explain complex findings clearly to non-technical stakeholders.',
      'Experience collaborating in cross-functional product teams.',
    ].join('\n'),
    niceToHave: [
      'Hands-on Python or R for statistical analysis.',
      'Experience in SaaS collaboration or developer tooling products.',
    ].join('\n'),
    applicationMode: 'both',
    externalApplyUrl:
      'https://www.linkedin.com/jobs/search/?keywords=Senior%20Product%20Analyst%20Atlassian',
    easyApplyEmail: 'careers@atlassian.com',
    easyApplyFields: {
      collectName: true,
      collectEmail: true,
      collectCv: true,
      collectLinkedin: true,
      collectCoverLetter: false,
    },
    applicationDeadline: daysFromNowIso(26),
    contactName: 'Atlassian Talent Team',
    postedByEmail: 'jobs@dawsydney.org.au',
    postedByUserId: null,
    stripeCheckoutSessionId: null,
    publishedAt: atlassianPublishedAt,
    publishExpiresAt: daysFromNowIso(85),
    reviewNote: null,
    lastReviewedByEmail: null,
    lastReviewedAt: null,
    createdAt: atlassianPublishedAt,
    updatedAt: daysAgoIso(1),
  },
  {
    id: 'sample-manager-risk-analytics-commonwealth-bank',
    slug: 'manager-risk-analytics-commonwealth-bank',
    status: 'published',
    packageType: 'standard',
    paymentStatus: 'paid',
    title: 'Manager, Risk Analytics',
    companyName: 'Commonwealth Bank',
    companyWebsite: 'https://www.commbank.com.au',
    brandLogoUrl: null,
    brandPrimaryColor: '#ffcc00',
    brandSecondaryColor: '#111827',
    locationText: 'Sydney, NSW',
    locationMode: 'onsite',
    employmentType: 'full-time',
    seniorityLevel: 'manager',
    salaryMin: 180000,
    salaryMax: 235000,
    salaryCurrency: 'AUD',
    salaryPeriod: 'year',
    summary:
      'Lead a risk analytics team delivering credit and portfolio insights across consumer lending, with a focus on forecasting, controls, and regulatory-grade reporting.',
    responsibilities: [
      'Lead analysts delivering risk performance and exposure reporting.',
      'Develop monitoring frameworks for delinquency, impairment, and portfolio trends.',
      'Collaborate with risk, finance, and technology teams on model outputs and controls.',
      'Drive uplift of risk data assets and documentation standards.',
      'Present risk insights and recommendations to senior governance forums.',
    ].join('\n'),
    requirements: [
      '7+ years in risk analytics, credit analytics, or banking analytics.',
      'Strong SQL and data modeling capability in enterprise data environments.',
      'Experience with credit risk reporting and control frameworks.',
      'Demonstrated people leadership and stakeholder management.',
      'Excellent written and verbal communication skills.',
    ].join('\n'),
    niceToHave: [
      'Exposure to IFRS 9 / CECL style expected credit loss frameworks.',
      'Experience with Python-based risk analytics workflows.',
    ].join('\n'),
    applicationMode: 'both',
    externalApplyUrl:
      'https://www.linkedin.com/jobs/search/?keywords=Manager%20Risk%20Analytics%20Commonwealth%20Bank',
    easyApplyEmail: 'careers@cba.com.au',
    easyApplyFields: {
      collectName: true,
      collectEmail: true,
      collectCv: true,
      collectLinkedin: true,
      collectCoverLetter: true,
    },
    applicationDeadline: daysFromNowIso(24),
    contactName: 'CBA Talent Acquisition',
    postedByEmail: 'jobs@dawsydney.org.au',
    postedByUserId: null,
    stripeCheckoutSessionId: null,
    publishedAt: commbankPublishedAt,
    publishExpiresAt: daysFromNowIso(86),
    reviewNote: null,
    lastReviewedByEmail: null,
    lastReviewedAt: null,
    createdAt: commbankPublishedAt,
    updatedAt: daysAgoIso(1),
  },
  {
    id: 'sample-staff-data-scientist-doordash',
    slug: 'staff-data-scientist-doordash',
    status: 'published',
    packageType: 'amplified',
    paymentStatus: 'paid',
    title: 'Staff Data Scientist, Marketplace',
    companyName: 'DoorDash',
    companyWebsite: 'https://www.doordash.com',
    brandLogoUrl: null,
    brandPrimaryColor: '#ff3008',
    brandSecondaryColor: '#d22a09',
    locationText: 'Melbourne, VIC (Hybrid)',
    locationMode: 'hybrid',
    employmentType: 'full-time',
    seniorityLevel: 'lead',
    salaryMin: 200000,
    salaryMax: 260000,
    salaryCurrency: 'AUD',
    salaryPeriod: 'year',
    summary:
      'Shape marketplace strategy through causal analysis, forecasting, and experimentation that improves delivery quality, merchant outcomes, and customer retention.',
    responsibilities: [
      'Partner with product and operations leaders to prioritize marketplace bets.',
      'Build and productionize predictive and causal models for supply-demand balancing.',
      'Design experiments and quasi-experiments for pricing and logistics initiatives.',
      'Develop reusable metric frameworks for service quality and efficiency.',
      'Mentor data scientists and raise analytical standards across teams.',
    ].join('\n'),
    requirements: [
      '8+ years in data science, applied econometrics, or quantitative analytics.',
      'Strong Python, SQL, and experimental design capability.',
      'Experience with marketplace, logistics, or pricing analytics.',
      'Ability to communicate technical tradeoffs to product and business leaders.',
      'Track record delivering measurable product or operational impact.',
    ].join('\n'),
    niceToHave: [
      'Experience with geospatial analytics and routing data.',
      'Familiarity with real-time decision systems.',
    ].join('\n'),
    applicationMode: 'both',
    externalApplyUrl:
      'https://www.linkedin.com/jobs/search/?keywords=Staff%20Data%20Scientist%20DoorDash',
    easyApplyEmail: 'apac-talent@doordash.com',
    easyApplyFields: {
      collectName: true,
      collectEmail: true,
      collectCv: true,
      collectLinkedin: true,
      collectCoverLetter: false,
    },
    applicationDeadline: daysFromNowIso(30),
    contactName: 'DoorDash APAC Recruiting',
    postedByEmail: 'jobs@dawsydney.org.au',
    postedByUserId: null,
    stripeCheckoutSessionId: null,
    publishedAt: doordashPublishedAt,
    publishExpiresAt: daysFromNowIso(87),
    reviewNote: null,
    lastReviewedByEmail: null,
    lastReviewedAt: null,
    createdAt: doordashPublishedAt,
    updatedAt: daysAgoIso(1),
  },
  {
    id: 'sample-senior-consumer-insights-analyst-nike',
    slug: 'senior-consumer-insights-analyst-nike',
    status: 'published',
    packageType: 'standard',
    paymentStatus: 'paid',
    title: 'Senior Consumer Insights Analyst',
    companyName: 'Nike',
    companyWebsite: 'https://www.nike.com',
    brandLogoUrl: null,
    brandPrimaryColor: '#111111',
    brandSecondaryColor: '#2f2f2f',
    locationText: 'Sydney, NSW (Hybrid)',
    locationMode: 'hybrid',
    employmentType: 'full-time',
    seniorityLevel: 'senior',
    salaryMin: null,
    salaryMax: null,
    salaryCurrency: 'AUD',
    salaryPeriod: 'year',
    summary:
      'Partner with digital, merchandising, and brand teams to turn customer and channel data into actionable growth opportunities across the ANZ market.',
    responsibilities: [
      'Build recurring insight packs on consumer behavior and conversion trends.',
      'Support experiment design for site, app, and campaign optimization.',
      'Create audience and lifecycle segmentation frameworks for planning.',
      'Work with cross-functional teams to prioritize measurable growth initiatives.',
      'Present clear recommendations to marketing and commerce leadership.',
    ].join('\n'),
    requirements: [
      '5+ years in consumer, marketing, or commercial analytics.',
      'Strong SQL and dashboarding capability.',
      'Experience translating behavioral data into business recommendations.',
      'Strong communication skills across technical and commercial stakeholders.',
      'Comfort working in fast-paced retail or e-commerce environments.',
    ].join('\n'),
    niceToHave: [
      'Experience with product analytics event data.',
      'Experience in apparel, sports, or lifestyle brands.',
    ].join('\n'),
    applicationMode: 'both',
    externalApplyUrl:
      'https://www.linkedin.com/jobs/search/?keywords=Senior%20Consumer%20Insights%20Analyst%20Nike',
    easyApplyEmail: 'careers@nike.com',
    easyApplyFields: {
      collectName: true,
      collectEmail: true,
      collectCv: true,
      collectLinkedin: true,
      collectCoverLetter: false,
    },
    applicationDeadline: daysFromNowIso(27),
    contactName: 'Nike Talent Team',
    postedByEmail: 'jobs@dawsydney.org.au',
    postedByUserId: null,
    stripeCheckoutSessionId: null,
    publishedAt: nikePublishedAt,
    publishExpiresAt: daysFromNowIso(88),
    reviewNote: null,
    lastReviewedByEmail: null,
    lastReviewedAt: null,
    createdAt: nikePublishedAt,
    updatedAt: daysAgoIso(1),
  },
  {
    id: 'sample-principal-marketing-analytics-manager-apple',
    slug: 'principal-marketing-analytics-manager-apple',
    status: 'published',
    packageType: 'amplified',
    paymentStatus: 'paid',
    title: 'Principal Marketing Analytics Manager',
    companyName: 'Apple',
    companyWebsite: 'https://www.apple.com',
    brandLogoUrl: null,
    brandPrimaryColor: '#111827',
    brandSecondaryColor: '#374151',
    locationText: 'Sydney, NSW',
    locationMode: 'onsite',
    employmentType: 'full-time',
    seniorityLevel: 'director',
    salaryMin: null,
    salaryMax: null,
    salaryCurrency: 'AUD',
    salaryPeriod: 'year',
    summary:
      'Lead measurement strategy for integrated campaigns across digital and retail channels, ensuring investment and creative decisions are backed by robust performance evidence.',
    responsibilities: [
      'Define end-to-end campaign measurement frameworks and reporting standards.',
      'Lead incrementality, attribution, and MMM-aligned analysis for major launches.',
      'Partner with media, retail, and product teams to optimize go-to-market outcomes.',
      'Guide a team of analysts and mentor senior individual contributors.',
      'Communicate business impact and tradeoffs to executive stakeholders.',
    ].join('\n'),
    requirements: [
      '8+ years in marketing analytics or growth analytics leadership roles.',
      'Deep expertise in attribution and causal measurement methods.',
      'Strong SQL and analytics engineering fluency.',
      'Proven ability to influence senior stakeholders with data-driven narratives.',
      'Experience leading cross-functional analytical programs at scale.',
    ].join('\n'),
    niceToHave: [
      'Experience in consumer technology or premium retail brands.',
      'Hands-on experience with experimental design in omni-channel environments.',
    ].join('\n'),
    applicationMode: 'both',
    externalApplyUrl:
      'https://www.linkedin.com/jobs/search/?keywords=Principal%20Marketing%20Analytics%20Manager%20Apple',
    easyApplyEmail: 'careers@apple.com',
    easyApplyFields: {
      collectName: true,
      collectEmail: true,
      collectCv: true,
      collectLinkedin: true,
      collectCoverLetter: true,
    },
    applicationDeadline: daysFromNowIso(31),
    contactName: 'Apple Recruiting',
    postedByEmail: 'jobs@dawsydney.org.au',
    postedByUserId: null,
    stripeCheckoutSessionId: null,
    publishedAt: applePublishedAt,
    publishExpiresAt: daysFromNowIso(89),
    reviewNote: null,
    lastReviewedByEmail: null,
    lastReviewedAt: null,
    createdAt: applePublishedAt,
    updatedAt: applePublishedAt,
  },
];
